#include "index/procfs.hpp"

#include "drivers/stiyl_magnus.hpp"
#include "index/dark_matter.hpp"
#include "index/esper.hpp"
#include "index/imaginary_number_district.hpp"
#include "index/last_order.hpp"
#include "index/misaka_network.hpp"
#include "index/testament.hpp" // real tmpfs mount list for /proc/mounts
#include "index/tree_diagram.hpp"
#include "index/usermode.hpp"

namespace index {

namespace district = imaginary_number_district;

} // namespace index

namespace index {

namespace {

// Each "file" in /proc is generated by a function that writes into a buffer.
// We materialise the bytes once per open via lateran_read_file; cap is the
// user buffer size.

bool str_eq(const char *a, const char *b) {
    while (*a && *b && *a == *b) { ++a; ++b; }
    return *a == 0 && *b == 0;
}

bool starts_with(const char *s, const char *p) {
    while (*p) {
        if (*s != *p) return false;
        ++s; ++p;
    }
    return true;
}

uint32_t append(char *buf, uint32_t cap, uint32_t off, const char *s) {
    while (*s && off < cap) buf[off++] = *s++;
    return off;
}

uint32_t append_u64(char *buf, uint32_t cap, uint32_t off, uint64_t v) {
    char tmp[24]; uint32_t n = 0;
    if (v == 0) { tmp[n++] = '0'; }
    else { while (v && n < sizeof(tmp)) { tmp[n++] = static_cast<char>('0' + (v % 10)); v /= 10; } }
    while (n-- && off < cap) buf[off++] = tmp[n];
    return off;
}

uint32_t append_hex64(char *buf, uint32_t cap, uint32_t off, uint64_t v) {
    static const char *kHex = "0123456789abcdef";
    char tmp[16]; uint32_t n = 0;
    if (v == 0) { tmp[n++] = '0'; }
    else { while (v && n < sizeof(tmp)) { tmp[n++] = kHex[v & 0xf]; v >>= 4; } }
    while (n-- && off < cap) buf[off++] = tmp[n];
    return off;
}

// ---- file generators ----

uint32_t gen_cpuinfo(char *buf, uint32_t cap) {
    uint32_t o = 0;
    const uint32_t cores = misaka_network_online_cpus();
    for (uint32_t i = 0; i < cores; ++i) {
        o = append(buf, cap, o, "processor\t: ");
        o = append_u64(buf, cap, o, i);
        o = append(buf, cap, o, "\nBogoMIPS\t: 125.00\n");
        o = append(buf, cap, o, "Features\t: fp asimd\n");
        o = append(buf, cap, o, "CPU implementer\t: 0x41\n");
        o = append(buf, cap, o, "CPU architecture: 8\n");
        o = append(buf, cap, o, "CPU variant\t: 0x0\n");
        o = append(buf, cap, o, "CPU part\t: 0xd03\n"); // Cortex-A53-ish
        o = append(buf, cap, o, "CPU revision\t: 0\n\n");
    }
    return o;
}

// Index-specific resource counters for leak monitoring. cat /proc/index_
// resources before/after repeated work; every line should plateau. This is
// the standing version of the ad-hoc "exit-time resource dump" used to prove
// the OOM fix had no siblings (mirrors Linux /proc/slabinfo + /proc/meminfo).
uint32_t gen_index_resources(char *buf, uint32_t cap) {
    uint32_t o = 0;
    const DarkMatterStats h = dark_matter_stats();
    o = append(buf, cap, o, "heap_used_bytes: ");  o = append_u64(buf, cap, o, h.used);
    o = append(buf, cap, o, "\nheap_free_bytes: "); o = append_u64(buf, cap, o, h.free_bytes);
    o = append(buf, cap, o, "\nheap_allocs: ");     o = append_u64(buf, cap, o, h.allocations);
    o = append(buf, cap, o, "\nheap_frees: ");      o = append_u64(buf, cap, o, h.frees);
    o = append(buf, cap, o, "\nheap_inflight: ");   o = append_u64(buf, cap, o, h.allocations - h.frees);
    o = append(buf, cap, o, "\npages_used: ");      o = append_u64(buf, cap, o, tree_diagram_used_pages());
    o = append(buf, cap, o, "\npages_total: ");     o = append_u64(buf, cap, o, tree_diagram_total_pages());
    // Esper slots by state (free/ready/running/waiting/exited/faulted = 0..5).
    uint32_t st[6] = {0};
    for (uint32_t i = 0; i < kMaxEspers; ++i) {
        Esper *e = esper_at(i);
        if (e != nullptr) {
            const uint32_t s = static_cast<uint32_t>(e->state);
            if (s < 6) ++st[s];
        }
    }
    o = append(buf, cap, o, "\nesper_ready: ");   o = append_u64(buf, cap, o, st[1]);
    o = append(buf, cap, o, "\nesper_running: "); o = append_u64(buf, cap, o, st[2]);
    o = append(buf, cap, o, "\nesper_waiting: "); o = append_u64(buf, cap, o, st[3]);
    o = append(buf, cap, o, "\nesper_exited: ");  o = append_u64(buf, cap, o, st[4]);
    o = append(buf, cap, o, "\nesper_faulted: "); o = append_u64(buf, cap, o, st[5]);
    o = append(buf, cap, o, "\nesper_live: ");    o = append_u64(buf, cap, o, st[1] + st[2] + st[3]);
    o = append(buf, cap, o, "\nas_refs_active: ");    o = append_u64(buf, cap, o, as_ref_active_count());
    o = append(buf, cap, o, "\nimage_refs_active: "); o = append_u64(buf, cap, o, image_ref_active_count());
    o = append(buf, cap, o, "\n");
    return o;
}

uint32_t gen_meminfo(char *buf, uint32_t cap) {
    const uint64_t pages_total = tree_diagram_total_pages();
    const uint64_t pages_used = tree_diagram_used_pages();
    const uint64_t total_kb = pages_total * 4; // 4 KiB pages
    const uint64_t used_kb = pages_used * 4;
    const uint64_t free_kb = (total_kb > used_kb) ? total_kb - used_kb : 0;
    uint32_t o = 0;
    o = append(buf, cap, o, "MemTotal:       ");
    o = append_u64(buf, cap, o, total_kb);
    o = append(buf, cap, o, " kB\nMemFree:        ");
    o = append_u64(buf, cap, o, free_kb);
    o = append(buf, cap, o, " kB\nMemAvailable:   ");
    o = append_u64(buf, cap, o, free_kb);
    o = append(buf, cap, o, " kB\nBuffers:               0 kB\nCached:                0 kB\n");
    o = append(buf, cap, o, "SwapTotal:             0 kB\nSwapFree:              0 kB\n");
    return o;
}

uint32_t gen_uptime(char *buf, uint32_t cap) {
    // last_order_ticks runs at 100 Hz. Idle is unknown -- report 0.0 like a
    // freshly-booted box, which is true here anyway.
    const uint64_t ticks = last_order_ticks();
    const uint64_t sec = ticks / 100;
    const uint32_t cs = static_cast<uint32_t>(ticks % 100);
    uint32_t o = 0;
    o = append_u64(buf, cap, o, sec);
    if (o < cap) buf[o++] = '.';
    if (cs < 10 && o < cap) buf[o++] = '0';
    o = append_u64(buf, cap, o, cs);
    o = append(buf, cap, o, " 0.00\n");
    return o;
}

uint32_t gen_version(char *buf, uint32_t cap) {
    return append(buf, cap, 0,
        "Linux version 5.0.0-arm-Index (crowley@academy-city) "
        "(arm-Index synth) #1 SMP\n");
}

uint32_t gen_cmdline(char *buf, uint32_t cap) {
    return append(buf, cap, 0, "console=ttyAMA0 root=/dev/vda1 rw\n");
}

uint32_t gen_hostname(char *buf, uint32_t cap) {
    return append(buf, cap, 0, "arm-index\n");
}

uint32_t gen_mounts(char *buf, uint32_t cap) {
    // We don't track a real mount table -- everything is Lateran/ext2 + procfs
    // + the 9p /host prefix. Emit the canonical entries so `mount` and tools
    // reading /proc/mounts (containers, package installers) see a plausible
    // layout. Format per `man proc(5)` mounts: dev mountpoint fstype opts 0 0.
    uint32_t o = 0;
    o = append(buf, cap, o, "/dev/vda1 / ext2 rw,relatime 0 1\n");
    o = append(buf, cap, o, "proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0\n");
    o = tmpfs_proc_mounts(buf, cap, o); // real tmpfs mounts (Testament): /tmp, /dev/shm, ...
    o = append(buf, cap, o, "devpts /dev/pts devpts rw,nosuid,noexec,relatime 0 0\n");
    if (drivers::stiyl_magnus_status().present) {
        o = append(buf, cap, o, "hostshare /host 9p rw,trans=virtio,version=9p2000.L 0 0\n");
    }
    return o;
}

uint32_t gen_kmsg(char *buf, uint32_t cap) {
    return district::kmsg_read(buf, cap);
}

// Walk Espers and return the one matching pid, or nullptr.
Esper *esper_by_pid(uint32_t pid) {
    for (uint32_t i = 0; i < kMaxEspers; ++i) {
        Esper *e = esper_at(i);
        if (e != nullptr && e->pid == pid && e->state != EsperState::free) {
            return e;
        }
    }
    return nullptr;
}

const char *state_letter(EsperState s) {
    switch (s) {
        case EsperState::running: return "R (running)";
        case EsperState::ready:   return "R (ready)";
        case EsperState::waiting: return "S (sleeping)";
        case EsperState::exited:  return "Z (zombie)";
        case EsperState::faulted: return "X (faulted)";
        case EsperState::free:    return "- (free)";
    }
    return "?";
}

// Generic generators that take an Esper *; self/* and <pid>/* share these.

uint32_t gen_pid_status(Esper *me, char *buf, uint32_t cap) {
    uint32_t o = 0;
    o = append(buf, cap, o, "Name:\t");
    o = append(buf, cap, o, me != nullptr ? me->name : "(kernel)");
    o = append(buf, cap, o, "\nState:\t");
    o = append(buf, cap, o, me != nullptr ? state_letter(me->state) : "?");
    o = append(buf, cap, o, "\nPid:\t");
    o = append_u64(buf, cap, o, me != nullptr ? me->pid : 0);
    o = append(buf, cap, o, "\nPPid:\t");
    o = append_u64(buf, cap, o, (me != nullptr && me->parent >= 0)
                                    ? esper_at(static_cast<uint32_t>(me->parent))->pid : 0);
    o = append(buf, cap, o, "\nUid:\t");
    o = append_u64(buf, cap, o, me != nullptr ? me->uid : 0);
    o = append(buf, cap, o, "\t");
    o = append_u64(buf, cap, o, me != nullptr ? me->euid : 0);
    o = append(buf, cap, o, "\t");
    o = append_u64(buf, cap, o, me != nullptr ? me->suid : 0);
    o = append(buf, cap, o, "\t0\nGid:\t");
    o = append_u64(buf, cap, o, me != nullptr ? me->gid : 0);
    o = append(buf, cap, o, "\t");
    o = append_u64(buf, cap, o, me != nullptr ? me->egid : 0);
    o = append(buf, cap, o, "\t");
    o = append_u64(buf, cap, o, me != nullptr ? me->sgid : 0);
    o = append(buf, cap, o, "\t0\nThreads:\t1\n");
    return o;
}

uint32_t gen_pid_maps(Esper *me, char *buf, uint32_t cap) {
    uint32_t o = 0;
    if (me == nullptr || me->mm == nullptr) return 0;
    const PersonalReality *mm = me->mm;
    for (uint32_t i = 0; i < mm->vma_count && o < cap; ++i) {
        const Vma &v = mm->vmas[i];
        if (v.kind == VmaKind::Free) continue;
        o = append_hex64(buf, cap, o, v.start);
        if (o < cap) buf[o++] = '-';
        o = append_hex64(buf, cap, o, v.end);
        if (o < cap) buf[o++] = ' ';
        // perms r/w/x/p
        if (o < cap) buf[o++] = (v.prot & kVmaProtR) ? 'r' : '-';
        if (o < cap) buf[o++] = (v.prot & kVmaProtW) ? 'w' : '-';
        if (o < cap) buf[o++] = (v.prot & kVmaProtX) ? 'x' : '-';
        if (o < cap) buf[o++] = 'p';
        o = append(buf, cap, o, " 00000000 00:00 0 ");
        // label
        const char *label = "[anon]";
        switch (v.kind) {
            case VmaKind::Stack: label = "[stack]"; break;
            case VmaKind::Brk:   label = "[heap]"; break;
            case VmaKind::File:  label = "[file]"; break;
            default: break;
        }
        o = append(buf, cap, o, label);
        if (o < cap) buf[o++] = '\n';
    }
    return o;
}

uint32_t gen_pid_cmdline(Esper *me, char *buf, uint32_t cap) {
    if (me == nullptr) return 0;
    uint32_t o = append(buf, cap, 0, me->name);
    if (o < cap) buf[o++] = 0; // argv strings are NUL-separated on real /proc
    return o;
}

uint32_t gen_pid_exe(Esper *me, char *buf, uint32_t cap) {
    // Real /proc/<pid>/exe is a symlink to the executable. We synthesise the
    // target string -- the readlinkat path treats this entry as content.
    if (me == nullptr) return 0;
    uint32_t o = 0;
    if (me->name[0] != '/') o = append(buf, cap, o, "/bin/");
    return append(buf, cap, o, me->name);
}

uint32_t gen_pid_cwd(Esper *me, char *buf, uint32_t cap) {
    if (me == nullptr) return 0;
    return append(buf, cap, 0, me->cwd[0] ? me->cwd : "/");
}

// /proc/<pid>/stat -- the single-line format busybox ps and top parse. Linux
// has ~52 fields; we fill the leading ones with real values and zero-pad the
// rest so positional parsers (kernel macro PROC_PID_STAT) stay happy.
//
//   field 1  pid
//   field 2  (comm)
//   field 3  state letter
//   field 4  ppid
//   fields 5-13: pgrp session tty_nr tpgid flags minflt cminflt majflt cmajflt
//   field 14 utime, 15 stime, 16 cutime, 17 cstime, 18 priority, 19 nice
//   field 20 num_threads, 21 itrealvalue, 22 starttime
//   field 23 vsize, 24 rss, then ~28 more we leave zero
uint32_t gen_pid_stat(Esper *me, char *buf, uint32_t cap) {
    if (me == nullptr) return 0;
    uint32_t o = 0;
    o = append_u64(buf, cap, o, me->pid);                            // 1 pid
    o = append(buf, cap, o, " (");
    o = append(buf, cap, o, me->name[0] ? me->name : "?");
    o = append(buf, cap, o, ") ");
    char st = '?';
    switch (me->state) {
        case EsperState::running: st = 'R'; break;
        case EsperState::ready:   st = 'R'; break;
        case EsperState::waiting: st = 'S'; break;
        case EsperState::exited:  st = 'Z'; break;
        case EsperState::faulted: st = 'X'; break;
        case EsperState::free:    st = '?'; break;
    }
    if (o < cap) buf[o++] = st;                                      // 3 state
    if (o < cap) buf[o++] = ' ';
    const uint32_t ppid = (me->parent >= 0)
        ? esper_at(static_cast<uint32_t>(me->parent))->pid : 0;
    o = append_u64(buf, cap, o, ppid);                               // 4 ppid
    // fields 5..13: nine zeros (pgrp session tty_nr tpgid flags minflt cminflt majflt cmajflt)
    for (int i = 0; i < 9; ++i) o = append(buf, cap, o, " 0");
    // field 14 utime, 15 stime, 16 cutime, 17 cstime, 18 priority(20), 19 nice
    o = append(buf, cap, o, " 0 0 0 0 20 0");
    // field 20 num_threads
    o = append(buf, cap, o, " 1");
    // field 21 itrealvalue, 22 starttime
    o = append(buf, cap, o, " 0 0");
    // field 23 vsize (bytes), 24 rss (pages)
    uint64_t vsize = 0;
    uint64_t rss_pages = 0;
    if (me->mm != nullptr) {
        for (uint32_t i = 0; i < me->mm->vma_count; ++i) {
            const Vma &v = me->mm->vmas[i];
            if (v.kind == VmaKind::Free) continue;
            vsize += (v.end - v.start);
            rss_pages += (v.end - v.start) / 4096; // overestimate (counts unmapped)
        }
    }
    if (o < cap) buf[o++] = ' ';
    o = append_u64(buf, cap, o, vsize);
    if (o < cap) buf[o++] = ' ';
    o = append_u64(buf, cap, o, rss_pages);
    // fields 25 rsslim, 26 startcode, 27 endcode: zero.
    o = append(buf, cap, o, " 0 0 0");
    // field 28 startstack: HotSpot's os::Linux::capture_initial_stack() reads
    // this to locate the primordial (main) thread stack base. Give it the
    // initial SP region top -- without it HotSpot warns "Can't detect primordial
    // thread stack location" and can't set up stack-overflow guard pages.
    if (o < cap) buf[o++] = ' ';
    o = append_u64(buf, cap, o, me->stack_top);
    // fields 29..52 (24 fields): zero-pad so positional parsers don't trip.
    for (int i = 0; i < 24; ++i) o = append(buf, cap, o, " 0");
    if (o < cap) buf[o++] = '\n';
    return o;
}

// Self generators delegate to the pid generators with the running Esper.
Esper *self_esper() {
    const int idx = esper_running_index();
    return (idx >= 0) ? esper_at(static_cast<uint32_t>(idx)) : nullptr;
}

uint32_t gen_self_status(char *buf, uint32_t cap) { return gen_pid_status(self_esper(), buf, cap); }
uint32_t gen_self_maps(char *buf, uint32_t cap)   { return gen_pid_maps(self_esper(), buf, cap); }
uint32_t gen_self_cmdline(char *buf, uint32_t cap) { return gen_pid_cmdline(self_esper(), buf, cap); }
uint32_t gen_self_exe(char *buf, uint32_t cap)    { return gen_pid_exe(self_esper(), buf, cap); }
uint32_t gen_self_cwd(char *buf, uint32_t cap)    { return gen_pid_cwd(self_esper(), buf, cap); }
uint32_t gen_self_stat(char *buf, uint32_t cap)   { return gen_pid_stat(self_esper(), buf, cap); }

// ---- dispatch ----

struct Entry {
    const char *name;          // full /proc path
    bool is_dir;
    uint32_t (*gen)(char *, uint32_t);
};

const Entry kEntries[] = {
    {"/proc",            true,  nullptr},
    {"/proc/cpuinfo",    false, gen_cpuinfo},
    {"/proc/meminfo",    false, gen_meminfo},
    {"/proc/index_resources", false, gen_index_resources},
    {"/proc/uptime",     false, gen_uptime},
    {"/proc/version",    false, gen_version},
    {"/proc/cmdline",    false, gen_cmdline},
    {"/proc/hostname",   false, gen_hostname},
    {"/proc/kmsg",       false, gen_kmsg},
    {"/proc/mounts",     false, gen_mounts},
    {"/proc/self",       true,  nullptr},
    {"/proc/self/status", false, gen_self_status},
    {"/proc/self/stat",  false, gen_self_stat},   // HotSpot reads this for the primordial stack
    {"/proc/self/maps",  false, gen_self_maps},
    {"/proc/self/cmdline", false, gen_self_cmdline},
    {"/proc/self/exe",   false, gen_self_exe},
    {"/proc/self/cwd",   false, gen_self_cwd},
};
constexpr uint32_t kNumEntries = sizeof(kEntries) / sizeof(kEntries[0]);

const Entry *find_entry(const char *path) {
    for (uint32_t i = 0; i < kNumEntries; ++i) {
        if (str_eq(path, kEntries[i].name)) return &kEntries[i];
    }
    return nullptr;
}

// Per-pid leaf generators -- the file names a /proc/<pid> dir is willing to
// serve. Keep in sync with the dir-listing code below.
struct PidLeaf {
    const char *name;
    uint32_t (*gen)(Esper *, char *, uint32_t);
};
const PidLeaf kPidLeaves[] = {
    {"status",  gen_pid_status},
    {"stat",    gen_pid_stat},
    {"maps",    gen_pid_maps},
    {"cmdline", gen_pid_cmdline},
    {"exe",     gen_pid_exe},
    {"cwd",     gen_pid_cwd},
};
constexpr uint32_t kNumPidLeaves = sizeof(kPidLeaves) / sizeof(kPidLeaves[0]);

// Try to decode /proc/<digits>(/<leaf>)?. Returns -1 if not a pid path; on
// success writes the pid and (if present) the leaf name pointer (else NULL).
int32_t parse_pid_path(const char *path, uint32_t *out_pid, const char **out_leaf) {
    *out_leaf = nullptr;
    if (!starts_with(path, "/proc/")) return -1;
    const char *p = path + 6;
    if (*p < '0' || *p > '9') return -1; // not a pid
    uint32_t pid = 0;
    while (*p >= '0' && *p <= '9') { pid = pid * 10 + (*p - '0'); ++p; }
    if (pid == 0) return -1;
    if (*p == 0) { *out_pid = pid; return 0; }    // /proc/<pid>
    if (*p != '/') return -1;
    *out_leaf = p + 1;
    *out_pid = pid;
    return 0;
}

} // namespace

bool procfs_owns_path(const char *path) {
    if (path == nullptr) return false;
    return starts_with(path, "/proc");
}

int64_t procfs_read_file(const char *path, char *buf, uint32_t cap) {
    // /proc/<pid>/<leaf>: synthesise from the named Esper.
    uint32_t pid = 0;
    const char *leaf = nullptr;
    if (parse_pid_path(path, &pid, &leaf) == 0 && leaf != nullptr) {
        Esper *e = esper_by_pid(pid);
        if (e == nullptr) return -1;
        for (uint32_t i = 0; i < kNumPidLeaves; ++i) {
            if (str_eq(leaf, kPidLeaves[i].name)) {
                return static_cast<int64_t>(kPidLeaves[i].gen(e, buf, cap));
            }
        }
        return -1;
    }
    const Entry *e = find_entry(path);
    if (e == nullptr || e->is_dir || e->gen == nullptr) return -1;
    return static_cast<int64_t>(e->gen(buf, cap));
}

bool procfs_is_dir(const char *path) {
    uint32_t pid = 0;
    const char *leaf = nullptr;
    if (parse_pid_path(path, &pid, &leaf) == 0 && leaf == nullptr) {
        // /proc/<pid> itself: directory if the process exists.
        return esper_by_pid(pid) != nullptr;
    }
    const Entry *e = find_entry(path);
    return e != nullptr && e->is_dir;
}

int64_t procfs_file_size(const char *path) {
    char tmp[2048];
    const int64_t n = procfs_read_file(path, tmp, sizeof(tmp));
    return (n >= 0) ? n : -1;
}

// Append one LateranEntry with the given name/dir flag. Returns next index.
uint32_t emit_entry(LateranEntry *out, uint32_t count, uint32_t max,
                    const char *name, bool is_dir) {
    if (count >= max) return count;
    LateranEntry &le = out[count];
    uint32_t j = 0;
    while (name[j] && j + 1 < sizeof(le.name)) { le.name[j] = name[j]; ++j; }
    le.name[j] = 0;
    le.size = 0;
    le.first_cluster = 0;
    le.is_dir = is_dir;
    le.uid = 0; le.gid = 0;
    le.mode = is_dir ? (0x4000u | 0555u) : (0x8000u | 0444u);
    return count + 1;
}

void u64_to_dec(uint64_t v, char *out) {
    char tmp[24]; uint32_t n = 0;
    if (v == 0) { tmp[n++] = '0'; }
    else { while (v && n < sizeof(tmp)) { tmp[n++] = static_cast<char>('0' + (v % 10)); v /= 10; } }
    uint32_t o = 0;
    while (n--) out[o++] = tmp[n];
    out[o] = 0;
}

uint32_t procfs_list_dir(const char *path, LateranEntry *out, uint32_t max) {
    if (path == nullptr) return 0;

    // /proc/<pid> directory: list the per-process leaves.
    uint32_t pid = 0;
    const char *leaf = nullptr;
    if (parse_pid_path(path, &pid, &leaf) == 0 && leaf == nullptr) {
        if (esper_by_pid(pid) == nullptr) return 0;
        uint32_t count = 0;
        for (uint32_t i = 0; i < kNumPidLeaves; ++i) {
            count = emit_entry(out, count, max, kPidLeaves[i].name, false);
        }
        return count;
    }

    const char *prefix = nullptr;
    uint32_t plen = 0;
    if (str_eq(path, "/proc")) { prefix = "/proc/"; plen = 6; }
    else if (str_eq(path, "/proc/self")) { prefix = "/proc/self/"; plen = 11; }
    else return 0;

    uint32_t count = 0;
    for (uint32_t i = 0; i < kNumEntries && count < max; ++i) {
        const char *name = kEntries[i].name;
        if (!starts_with(name, prefix)) continue;
        const char *rest = name + plen;
        if (*rest == 0) continue; // the directory itself
        const char *q = rest;
        while (*q && *q != '/') ++q;
        if (*q == '/') continue; // skip deeper paths
        bool dup = false;
        for (uint32_t k = 0; k < count; ++k) {
            if (str_eq(out[k].name, rest)) { dup = true; break; }
        }
        if (dup) continue;
        count = emit_entry(out, count, max, rest, kEntries[i].is_dir);
    }

    // /proc root: also enumerate live process directories.
    if (str_eq(path, "/proc")) {
        for (uint32_t i = 0; i < kMaxEspers && count < max; ++i) {
            Esper *e = esper_at(i);
            if (e == nullptr || e->state == EsperState::free) continue;
            char buf[16];
            u64_to_dec(e->pid, buf);
            count = emit_entry(out, count, max, buf, true);
        }
    }
    return count;
}

} // namespace index
